FROM cloudron/base:5.0.0

RUN mkdir -p /app/code
WORKDIR /app/code

# copy package.json in isolation to detect changes
ADD package.json /app/code
RUN npm install

ADD . /app/code

ENV PORT 3000
EXPOSE 3000

CMD [ "/app/code/cloudron-start.sh" ]
