FROM cloudron/base:5.0.0@sha256:04fd70dbd8ad6149c19de39e35718e024417c3e01dc9c6637eaf4a41ec4e596c

RUN mkdir -p /app/code
WORKDIR /app/code

# copy package.json in isolation to detect changes
ADD package.json /app/code
RUN npm install

ADD . /app/code

ENV PORT 3000
EXPOSE 3000

CMD [ "/app/code/start.sh" ]
